### PR TITLE
Add hint field for entry type and mask (#2588)

### PR DESCRIPTION
**Pull request by guilhermocc**
Add Hint field to `Entry` and `EntryMask ` messages, following the definition of  https://github.com/spiffe/spiffe/pull/179 and https://github.com/spiffe/spire/issues/2588.

### CODE REVIEW

**Comment by azdagron** [comment]
The SDK repo's are a bit different. PRs always target the `next` repo. We then move stuff into main before doing a release. Can you retarget this PR to `next`?

**Comment by azdagron** [comment]
I just retargetted it and now there are conflicts .... hmmm.

**Comment by guilhermocc** [comment]
Thank you, @azdagron! I've successfully rebased this branch :)

**Review by azdagron — APPROVED** [review]
\o/, thanks @guilhermocc !

**Pull request merged**
